### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/partyreviews/1


### 모임 후기 전체 조회
GET http://localhost:8080/partyboards/1/partyreviews

### 모임 후기 작성
POST http://localhost:8080/partyboards/1/partyreviews
Content-Type: application/json;application/json;charset=UTF-8

{
  "partyBoardNumber": 1,
  "partyReviewRate": 5,
  "partyReviewDetail": "참 좋은 모임이었어요!"
}

### 모임 후기 수정
PUT http://localhost:8080/partyboards/1/partyreviews/14
Content-Type: application/json;application/json;charset=UTF-8

{
  "partyReviewRate" : 4,
  "partyReviewDetail" : "testPartyReviewDetailModified"
}

### 모임 후기 삭제
DELETE http://localhost:8080/partyboards/1/partyreviews/13
