
### 취미 기반 모임 추천
GET http://localhost:8080/partyboards/recommended-parties?hobbyNumber=1&partyBoardNumber=1

### 인기 모임 전체 조회
GET http://localhost:8080/partyboards/popular-parties

### 모임 검색
GET http://localhost:8080/partyboards/search?keyword=workshop&isLikedOnly=true

###
GET http://localhost:8080/partyboards/search

###
GET http://localhost:8080/partyboards/search?sortMethod=oldest&cursor=100

### 조회순으로 정렬 기준 처음으로 바꿨을 때
GET http://localhost:8080/partyboards/search?sortMethod=mostLiked

### 관심사 Only
GET http://localhost:8080/partyboards/search?isLikedOnly=true

###
GET http://localhost:8080/partyboards/search?cursor=1&isLikedOnly=true

### 마지막 출력 카드번호 6번, 관심사 해당 모임만 출력, 조회수순
GET http://localhost:8080/partyboards/search?cursor=6&isLikedOnly=true&sortMethod=mostViewed


### 모임 상세 조회
GET http://localhost:8080/partyboards/1


### 모임 글 작성
POST http://localhost:8080/partyboards
Content-Type: application/json;charset=utf-8

{

}

### 모임 글 삭제
DELETE http://localhost:8080/partyboards/18

###
GET http://localhost:8080/img/partyboard/24/thumbnail/f9830f03c4b743079746c1287fd190c2.png

### 키워드 검색후 모임 결과 조회 + 페이지네이션
GET http://localhost:8081//search-whole/party?keyword=&page=0&size=4
